name: datatool
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.12
  - aiosignal=1.2.0
  - aria2=1.37.0
  - attrs=24.3.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.31
  - click=8.1.7
  - colorama=0.4.6
  - frozenlist=1.5.0
  - gmp=6.3.0
  - icu=75.1
  - idna=3.7
  - libcxx=19.1.7
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.17
  - liblzma=5.6.4
  - libopenblas=0.3.21
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - multidict=6.1.0
  - ncurses=6.5
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openssl=3.4.1
  - packaging=24.2
  - pip=25.0
  - polars=1.22.0
  - propcache=0.2.0
  - pygments=2.15.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - readline=8.2
  - rich=13.9.4
  - setuptools=72.1.0
  - shellingham=1.5.0
  - six=1.16.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wheel=0.45.1
  - xmltodict=0.14.2
  - yarl=1.18.0
