---
# Jaeger All-in-One for Local Development
# Distributed Tracing for Crypto Lakehouse
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
    component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.50
        ports:
        - containerPort: 16686  # Jaeger UI
          name: ui
        - containerPort: 14268  # Jaeger HTTP collector
          name: http-collector
        - containerPort: 14250  # Jaeger gRPC collector
          name: grpc-collector
        - containerPort: 9411   # Zipkin
          name: zipkin
        - containerPort: 14269  # Admin/metrics
          name: admin
        - containerPort: 6831   # UDP agent (compact)
          name: udp-compact
          protocol: UDP
        - containerPort: 6832   # UDP agent (binary)
          name: udp-binary
          protocol: UDP
        
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: METRICS_STORAGE_TYPE
          value: "prometheus"
        - name: PROMETHEUS_SERVER_URL
          value: "http://prometheus.observability:9090"
        - name: JAEGER_DISABLED
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            
        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 30
          periodSeconds: 30
          
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: observability
  labels:
    app: jaeger
    component: ui
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  labels:
    app: jaeger
    component: collector
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "14269"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: jaeger
  ports:
  - name: http-collector
    port: 14268
    targetPort: 14268
    protocol: TCP
  - name: grpc-collector
    port: 14250
    targetPort: 14250
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: 9411
    protocol: TCP
  - name: admin
    port: 14269
    targetPort: 14269
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: observability
  labels:
    app: jaeger
    component: agent
spec:
  selector:
    app: jaeger
  ports:
  - name: udp-compact
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: udp-binary
    port: 6832
    targetPort: 6832
    protocol: UDP
  type: ClusterIP

---
# Service Monitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
      component: collector
  endpoints:
  - port: admin
    interval: 30s
    path: /metrics